#!/bin/tcsh
module purge
module load cuda/v11.4
conda activate masterarbeit
python main.py --run_reverb=1 --model_struct=1 --training_epochs=300 --sequence_length=8 --output_sequence_length=4 --cqt_window_length=512 --learning_rate=0.00001
